---

- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Update all packages
      package:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install NVIDIA packages
      package:
        name:
          - kernel-devel
          - akmod-nvidia
          - xorg-x11-drv-nvidia-cuda
          - nvtop
        state: present

    - name: Enable NVIDIA power services
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - nvidia-hibernate
        - nvidia-suspend
        - nvidia-resume
        - nvidia-powerd

