---
- name: Install ASUS Linux tools and service
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Add COPR repository
      community.general.copr:
        name: lukenukem/asus-linux
        state: enabled

    - name: Install asusctl and supergfxctl
      package:
        name:
          - asusctl
          - supergfxctl
        state: present

    - name: Enable asusd.service and supergfxd.service
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - asusd
        - supergfxd

- name: Configure asusctl
  hosts: localhost
  connection: local
  tasks:
    - name: Set battery charge limit
      command: /usr/bin/asusctl -c 100

    - name: Enable keyboard lighting
      command: /usr/bin/asusctl aura-power keyboard --awake

    - name: Set keyboard lighting static
      command: /usr/bin/asusctl aura static

    - name: Disable slash lighting
      command: /usr/bin/asusctl slash --disable

- name: Add keyboard shortcut to cycle power mode
  hosts: localhost
  connection: local
  vars:
    cycle_power_mode_script_path: "/usr/local/bin/cycle_power_mode.sh"
    cycle_power_mode_name: "Cycle Power Mode"
    cycle_power_mode_command: "/usr/local/bin/cycle_power_mode.sh"
    cycle_power_mode_binding: "Launch4"
  tasks:
    - name: Copy cycle_power_mode.sh
      become: yes
      copy:
        src: cycle_power_mode.sh.j2
        dest: "{{ cycle_power_mode_script_path }}"
        mode: '0755'

    - name: Check which custom keybindings are already set
      command: gsettings get org.gnome.settings-daemon.plugins.media-keys custom-keybindings
      register: check_custom_keybindings

    - name: Add custom keyboard scheema key cycle-power-mode
      command: gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/cycle-power-mode/']"
      when: "'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/cycle-power-mode/' not in check_custom_keybindings.stdout"


    - name: Check cycle-power-mode key "name"
      command: gsettings get org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/cycle-power-mode/ name
      register: check_cycle_power_mode_name
      ignore_errors: yes

    - name: Set cycle-power-mode key "name"
      command: gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/cycle-power-mode/ name '{{ cycle_power_mode_name }}'
      when: "cycle_power_mode_name not in check_cycle_power_mode_name.stdout"


    - name: Check cycle-power-mode key "command"
      command: gsettings get org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/cycle-power-mode/ command
      register: check_cycle_power_mode_command
      ignore_errors: yes

    - name: Set cycle-power-mode key "command"
      command: gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/cycle-power-mode/ command '{{ cycle_power_mode_command }}'
      when: "cycle_power_mode_command not in check_cycle_power_mode_command.stdout"


    - name: Check cycle-power-mode key "binding"
      command: gsettings get org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/cycle-power-mode/ binding
      register: check_cycle_power_mode_binding
      ignore_errors: yes

    - name: Set cycle-power-mode key "binding"
      command: gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/cycle-power-mode/ binding '{{ cycle_power_mode_binding }}'
      when: "cycle_power_mode_binding not in check_cycle_power_mode_binding.stdout"
