---

- name: Install dconf-editor
  hosts: localhost
  connection: local
  tasks:

    - name: Install dconf-editor
      become: yes
      package:
        name:
          - dconf-editor # GUI Editor for gsettings schemas and keys
          - python3-psutil # required for dconf
        state: present

- name: Configure General Settings
  hosts: localhost
  connection: local
  tasks:

    - name: Disable screen dimming
      ansible.builtin.dconf:
        key: /org/gnome/settings-daemon/plugins/power/idle-dim
        value: false

    - name: Set Session Idle Time
      ansible.builtin.dconf:
        key: /org/gnome/desktop/session/idle-delay
        value: "uint32 1800"

    - name: Set Sleep Timeout (AC)
      ansible.builtin.dconf:
        key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout
        value: 10800

    - name: Set Sleep Timeout (Battery)
      ansible.builtin.dconf:
        key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-timeout
        value: 5400

    - name: Set Power Button Action
      ansible.builtin.dconf:
        key: /org/gnome/settings-daemon/plugins/power/power-button-action
        value: "'interactive'"

    - name: Set Show Battery Percentage
      ansible.builtin.dconf:
        key: /org/gnome/desktop/interface/show-battery-percentage
        value: true

    - name: Set Clock 24h Format
      ansible.builtin.dconf:
        key: /org/gnome/desktop/interface/clock-format
        value: "'24h'"

    - name: Set Clock Show Weekday
      ansible.builtin.dconf:
        key: /org/gnome/desktop/interface/clock-show-weekday
        value: true

    - name: Set Calendar Show Weekdate
      ansible.builtin.dconf:
        key: /org/gnome/desktop/calendar/show-weekdate
        value: true

    - name: Set Color Scheme Dark
      ansible.builtin.dconf:
        key: /org/gnome/desktop/interface/color-scheme
        value: "'prefer-dark'"

    - name: Set Static Hostname
      become: yes
      command: hostnamectl set-hostname "asus_rog_zephyrus"

    - name: Set button-layout
      ansible.builtin.dconf:
        key: "/org/gnome/desktop/wm/preferences/button-layout"
        value: "'appmenu:minimize,maximize,close'"

- name: Configure Gnome Terminal
  hosts: localhost
  connection: local
  tasks:

    - name: Read default profile UUID
      ansible.builtin.dconf:
        key: /org/gnome/Ptyxis/default-profile-uuid
        state: read
      register: default_profile_uuid

    - name: Set palette to xterm
      ansible.builtin.dconf:
        key: "/org/gnome/Ptyxis/Profiles/{{ default_profile_uuid.value }}/palette"
        value: "'xterm'"

    - name: Set use bright color for bold font
      ansible.builtin.dconf:
        key: "/org/gnome/Ptyxis/Profiles/{{ default_profile_uuid.value }}/bold-is-bright"
        value: true

    - name: Set restore window size
      ansible.builtin.dconf:
        key: "/org/gnome/Ptyxis/restore-window-size"
        value: true

    - name: Set fontsize
      ansible.builtin.dconf:
        key: "/org/gnome/Ptyxis/font-name"
        value: "'Monospace 12'"

- name: Gnome Extensions
  hosts: localhost
  connection: local
  tasks:

    - name: Install Tweaks and Extensions
      become: yes
      package:
        name:
          - gnome-tweaks
          - gnome-shell-extension-dash-to-panel
        state: present

    - name: Enable Dash to Panel extension
      command: gnome-extensions enable dash-to-panel@jderose9.github.com
      ignore_errors: yes  # Ignore errors if the extension is already enabled

    - name: Set appicon margin
      ansible.builtin.dconf:
        key: "/org/gnome/shell/extensions/dash-to-panel/appicon-margin"
        value: 4

    - name: Set panel hotkeys
      ansible.builtin.dconf:
        key: "/org/gnome/shell/extensions/dash-to-panel/hot-keys"
        value: true

    - name: Set shortcut previews
      ansible.builtin.dconf:
        key: "/org/gnome/shell/extensions/dash-to-panel/shortcut-previews"
        value: true

