---

- name: Install Syncthing
  hosts: localhost
  connection: local
  tasks:
    - name: Install Syncthing
      become: yes
      package:
        name:
          - syncthing 
        state: present

    - name: Create syncthing user
      become: yes
      user:
        name: syncthing
        system: yes
        create_home: yes
        shell: /bin/false

    - name: Copy syncthing service file
      become: yes
      copy:
        src: /usr/lib/systemd/system/syncthing@.service
        dest: /etc/systemd/system/syncthing@syncthing.service
        mode: '0644'
        remote_src: yes
      notify: reload systemd

    - name: Modify syncthing service file
      become: yes
      lineinfile:
        path: /etc/systemd/system/syncthing@syncthing.service
        regexp: '^User='
        line: 'User=syncthing'
        state: present
      notify: reload systemd

    - name: Enable and start syncthing service
      become: yes
      systemd:
        name: syncthing@syncthing.service
        enabled: yes
        state: started
        daemon_reload: yes

  handlers:
    - name: reload systemd
      become: yes
      systemd:
        daemon_reload: yes

- name: Configure Syncthing
  hosts: localhost
  connection: local
  become: yes
  become_user: syncthing
  vars:
    configuration_file_path: /home/syncthing/.local/state/syncthing/config.xml
  vars_prompt:

    - name: local_device_id
      prompt: What is the syncthing device id of this device?
      default: "LGKEUQR-UGCJBV6-DRYUJGA-RMHLHT3-5LRBVUJ-KAVG2UF-VE5FDL5-KQ44IQN"

    - name: mobile_device_id
      prompt: What is the syncthing device id of the mobile device?
      default: "G7C7IQD-IJSVW4S-XBKZWBF-PQIJCTP-YOCLBKW-A7PS6IV-OE4ID3N-HLMLBAZ"

    - name: keepass_folder_id
      prompt: What is the Folder ID for "Keepass"?
      default: y4he9-oio5q

  tasks:

    - name: Set syncthing device ID
      block:
        - name: Set device ID
          xml:
            path: "{{ configuration_file_path }}"
            xpath: "/configuration/device"
            attribute: id
            value: "{{ local_device_id }}"

        - name: Set device ID in default
          xml:
            path: "{{ configuration_file_path }}"
            xpath: "/configuration/defaults/folder/device"
            attribute: id
            value: "{{ local_device_id }}"

    - name: Add keypass_folder
      xml:
        path: "{{ configuration_file_path }}"
        xpath: /configuration
        add_children:
          - folder:
              id: "{{ keepass_folder_id }}"
              path: "/home/pagu/240801_keepass_syncthing"
              type: "sendreceive"
              rescanIntervalS: "3600"
              fsWatcherEnabled: "true"
              fsWatcherDelayS: "10"
              fsWatcherTimeoutS: "0"
              ignorePerms: "false"
              autoNormalize: "true"
              _:
                - filesystemType: "basic"
                - device:
                    id: "{{ local_device_id }}"
                    introducedBy: ""
                    _:
                      - encryptionPassword: ""
                - minDiskFree:
                    _: "32"
                    unit: "GB"
                - versioning:
                    _:
                      - cleanupIntervalS: "3600"
                      - fsPath: ""
                      - fsType: "basic"
                - copiers: "0"
                - pullerMaxPendingKiB: "0"
                - hashers: "0"
                - order: "random"
                - ignoreDelete: "false"
                - scanProgressIntervalS: "0"
                - pullerPauseS: "0"
                - maxConflicts: "10"
                - disableSparseFiles: "false"
                - disableTempIndexes: "false"
                - paused: "false"
                - weakHashThresholdPct: "25"
                - markerName: ".stfolder"
                - copyOwnershipFromParent: "false"
                - modTimeWindowS: "0"
                - maxConcurrentWrites: "2"
                - disableFsync: "false"
                - blockPullOrder: "standard"
                - copyRangeMethod: "standard"
                - caseSensitiveFS: "false"
                - junctionsAsDirs: "false"
                - syncOwnership: "false"
                - sendOwnership: "false"
                - syncXattrs: "false"
                - sendXattrs: "false"
                - xattrFilter:
                    _:
                      - maxSingleEntrySize: "1024"
                      - maxTotalSize: "4096"

