---

- name: Install Syncthing
  hosts: localhost
  connection: local
  tasks:
    - name: Install Syncthing
      become: yes
      package:
        name:
          - syncthing 
        state: present

    - name: Create syncthing user
      become: yes
      user:
        name: syncthing
        system: yes
        create_home: yes
        shell: /bin/false

    - name: Copy syncthing service file
      become: yes
      copy:
        src: /usr/lib/systemd/system/syncthing@.service
        dest: /etc/systemd/system/syncthing@syncthing.service
        mode: '0644'
        remote_src: yes
      notify: reload systemd

    - name: Modify syncthing service file
      become: yes
      lineinfile:
        path: /etc/systemd/system/syncthing@syncthing.service
        regexp: '^User='
        line: 'User=syncthing'
        state: present
      notify: reload systemd

    - name: Enable and start syncthing service
      become: yes
      systemd:
        name: syncthing@syncthing.service
        enabled: yes
        state: started
        daemon_reload: yes

  handlers:
    - name: reload systemd
      become: yes
      systemd:
        daemon_reload: yes

- name: Configure Syncthing
  hosts: localhost
  connection: local
  become: yes
  become_user: syncthing
  vars:
    configuration_file_path: /home/syncthing/.local/state/syncthing/config.xml
  vars_prompt:

    - name: syncthing_local_device_id
      prompt: What is the syncthing device id of this device?
      default: "LGKEUQR-UGCJBV6-DRYUJGA-RMHLHT3-5LRBVUJ-KAVG2UF-VE5FDL5-KQ44IQN"

    - name: syncthing_mobile_device_id
      prompt: What is the syncthing device id of the mobile device?
      default: "G7C7IQD-IJSVW4S-XBKZWBF-PQIJCTP-YOCLBKW-A7PS6IV-OE4ID3N-HLMLBAZ"

  tasks:

    - name: Set syncthing device ID
      block:
        - name: Set device ID
          xml:
            path: "{{ configuration_file_path }}"
            xpath: "/configuration/device"
            attribute: id
            value: "{{ syncthing_local_device_id }}"

        - name: Set device ID in default
          xml:
            path: "{{ configuration_file_path }}"
            xpath: "/configuration/defaults/folder/device"
            attribute: id
            value: "{{ syncthing_local_device_id }}"

