---

- name: Install Syncthing
  hosts: localhost
  connection: local
  tasks:
    - name: Install Syncthing
      become: yes
      package:
        name:
          - syncthing 
        state: present

    - name: Create syncthing user
      become: yes
      user:
        name: syncthing
        system: yes
        create_home: yes
        shell: /bin/false

    - name: Copy syncthing service file
      become: yes
      copy:
        src: /usr/lib/systemd/system/syncthing@.service
        dest: /etc/systemd/system/syncthing@syncthing.service
        mode: '0644'
        remote_src: yes
      notify: reload systemd

    - name: Modify syncthing service file
      become: yes
      lineinfile:
        path: /etc/systemd/system/syncthing@syncthing.service
        regexp: '^User='
        line: 'User=syncthing'
        state: present
      notify: reload systemd

    - name: Enable and start syncthing service
      become: yes
      systemd:
        name: syncthing@syncthing.service
        enabled: yes
        state: started
        daemon_reload: yes

  handlers:
    - name: reload systemd
      become: yes
      systemd:
        daemon_reload: yes

- name: Configure Syncthing
  hosts: localhost
  connection: local
  become: yes
  become_user: syncthing
  vars:
    configuration_file_path: /home/syncthing/.local/state/syncthing/config.xml
    syncthing_local_id: "LGKEUQR-UGCJBV6-DRYUJGA-RMHLHT3-5LRBVUJ-KAVG2UF-VE5FDL5-KQ44IQN"
  tasks:

    - name: Set syncthing device ID
      block:
        - name: Set device ID
          xml:
            xml: "{{ configuration_file_path }}"
            xpath: "/configuration/device"
            attributes:
              - name: "id"
                value: "{{ syncthing_local_id }}"

        - name: Set device ID in default
          xml:
            xml: "{{ configuration_file_path }}"
            xpath: "/configuration/defaults/folder/device"
            attributes:
              - name: "id"
                value: "{{ syncthing_local_id }}"

