---

- name: Install Syncthing
  hosts: localhost
  connection: local
  tasks:
    - name: Install Syncthing
      become: yes
      package:
        name:
          - syncthing 
        state: present

    - name: Create syncthing user
      become: yes
      user:
        name: syncthing
        groups: pagu
        append: yes
        system: yes
        create_home: yes
        shell: /bin/false

    - name: Add pagu to syncthing group
      become: yes
      user:
        name: pagu
        groups: syncthing
        append: yes

    - name: Copy syncthing service file
      become: yes
      copy:
        src: /usr/lib/systemd/system/syncthing@.service
        dest: /etc/systemd/system/syncthing@syncthing.service
        mode: '0644'
        remote_src: yes
      notify: reload systemd

    - name: Modify syncthing service file
      become: yes
      lineinfile:
        path: /etc/systemd/system/syncthing@syncthing.service
        regexp: '^User='
        line: 'User=syncthing'
        state: present
      notify: reload systemd

    - name: Enable and start syncthing service
      become: yes
      systemd:
        name: syncthing@syncthing.service
        enabled: yes
        state: started
        daemon_reload: yes

  handlers:
    - name: reload systemd
      become: yes
      systemd:
        daemon_reload: yes

- name: Configure Syncthing
  hosts: localhost
  connection: local
  vars:
    configuration_file_path: /home/syncthing/.local/state/syncthing/config.xml
    keepass_directory_path: /home/pagu/Documents/240801_keepass_syncthing
  vars_prompt:

    - name: local_device_id
      prompt: What is the syncthing device id of this device?
      default: "LGKEUQR-UGCJBV6-DRYUJGA-RMHLHT3-5LRBVUJ-KAVG2UF-VE5FDL5-KQ44IQN"

    - name: mobile_device_id
      prompt: What is the syncthing device id of the mobile device?
      default: "G7C7IQD-IJSVW4S-XBKZWBF-PQIJCTP-YOCLBKW-A7PS6IV-OE4ID3N-HLMLBAZ"

    - name: keepass_folder_id
      prompt: What is the Folder ID for "Keepass"?
      default: y4he9-oio5q

  tasks:

    - name: Set traverse pagu home
      become: yes
      file:
        path: /home/pagu
        owner: pagu
        group: pagu
        mode: '0710'

    - name: Set keepass directory group
      become: yes
      file:
        path: "{{ keepass_directory_path }}"
        owner: pagu
        group: syncthing
        mode: '0770'
        recurse: yes
