---

- hosts: localhost
  connection: local
  become: yes
  tasks:
  
    - name: Add COPR repository
      community.general.copr:
        name: lukenukem/asus-linux
        state: enabled

    - name: Install asusctl and supergfxctl
      package:
        name:
          - asusctl
          - supergfxctl
        state: present

    - name: Enable asusd.service and supergfxd.service
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - asusd
        - supergfxd

